version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true


[[rulesets]]
group = "负载均衡轮询"
ruleset = "[]FINAL"
# type = "surge-ruleset"
# interval = 86400
# ; custom_proxy_group=负载均衡轮询`load-balance`.*`http://www.gstatic.com/generate_204`300,,100

[[custom_groups]]
name = "负载均衡轮询"
type = "load-balance"
rule = [".*"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"
# ;设置分组标志位



# ;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

# ;luck
